sudo: false
language:
  - php
  - node_js

php:
  - 5.4

node_js:
  - 0.10

install:
  - composer install
  - npm install

script:
  - cd _test
  - phpunit --verbose --stderr
  - ../node_modules/karma/bin/karma start --single-run --browsers PhantomJS
