<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: richmahn
 * Date: Sun, 31 May 2015 17:32:44 +0000
 */

$conf['title'] = 'Door43';
$conf['start'] = 'home';
$conf['template'] = 'door43';
$conf['tagline'] = 'open discipleship resources';
$conf['license'] = 'cc-by-sa';
$conf['basedir'] = '/';
$conf['dmode'] = 0775;
$conf['fmode'] = 0664;
$conf['allowdebug'] = 1;
$conf['recent_days'] = 3650;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['deaccent'] = '2';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['securecookie'] = 0;
$conf['remote'] = 1;
$conf['cachetime'] = -1;
$conf['im_convert'] = '/usr/bin/convert';
$conf['jpg_quality'] = 90;
$conf['subscribers'] = 1;
$conf['notify'] = 'webmaster@test.door43.org';
$conf['registernotify'] = 'webmaster@test.door43.org';
$conf['mailfrom'] = 'dokuwiki@test.door43.org';
$conf['htmlmail'] = 0;
$conf['sitemap'] = 1;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['sepchar'] = '-';
$conf['fnencode'] = 'safe';
$conf['compress'] = 0;
$conf['send404'] = 1;
$conf['readdircache'] = -1;
$conf['dnslookups'] = 0;
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '';
$conf['plugin']['dw2pdf']['usecache'] = 0;
$conf['plugin']['markdownextra']['frontmatter'] = 1;
$conf['plugin']['captcha']['regprotect'] = 0;
$conf['plugin']['swiftmail']['smtp_host'] = 'mail.xsni.net';
$conf['plugin']['swiftmail']['smtp_port'] = 465;
$conf['plugin']['swiftmail']['smtp_ssl'] = '4';
$conf['plugin']['swiftmail']['auth_user'] = '';
$conf['plugin']['swiftmail']['auth_pass'] = '';
$conf['plugin']['pageredirect']['show_note'] = 0;
$conf['plugin']['pagelist']['showdate'] = '0';
$conf['plugin']['pagelist']['showuser'] = '0';
$conf['plugin']['pagelist']['showcomments'] = 1;
$conf['plugin']['pagelist']['sort'] = 1;
$conf['plugin']['graphviz']['path'] = '/usr/bin/dot';
$conf['plugin']['ckgedit']['guest_media'] = 0;
$conf['plugin']['ckgedit']['acl_del'] = 1;
$conf['plugin']['ckgedit']['direction'] = 'dokuwiki';
$conf['plugin']['ckgedit']['dw_priority'] = 1;
$conf['plugin']['door43gitmerge']['mergens'] = 'en';
$conf['plugin']['translation']['translations'] = 'bhj arz zmz ttt-x-ismai ttt-x-txizi bal prs lgg pgg ab abp abs ae af aii ak am an ar as av ay az ba be bg bh bi blx bm bn bnp bo br bs ca ce ch cnh co cr cs cu cv cy da de dv dz ee el en eo es et eu fa ff fi fj fo fr frd fy ga gaj gd gl gn gu gv ha he hi ho hr ht hu hy hz ia id ie ig ii ik ilo io is it iu ja jit jmd jv ka kg ki kj kk kl km kn ko kr ks ku kv kw ky la lb lg li lki ln lo loe lt lv mg mh mi mk ml mn mr ms mt my mzn na nb nd ne ng nl nn no nr nv nxl ny oc oj om or os pa pi pl ppq ps pt pt-br qu rm rn ro ru rw sa sc sd sdh se sg shn si sk sl slu sm sn so sq sr ss st su sv sw ta te tg th ti tk tl tn to tr ts tt tw ty ug uk ur uz ve vi vo wa wo xh xmf yao yi yo za zh zh-tw zu bho tdj ums dgo brx ktu lua kmb tll es-419 mgh';
$conf['plugin']['translation']['dropdown'] = '2';
$conf['plugin']['translation']['display'] = 'langcode,name';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['checkage'] = 1;
$conf['plugin']['translation']['localabout'] = 1;
$conf['plugin']['include']['showfooter'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showcomments'] = 0;
$conf['plugin']['include']['showlinkbacks'] = 0;
$conf['plugin']['include']['showtags'] = 0;
$conf['plugin']['rater']['voting_restriction'] = 1;
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['useavatar'] = 0;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['ditaa']['java'] = '/usr/bin/java';
$conf['plugin']['tag']['sortkey'] = 'pagename';
$conf['plugin']['tag']['toolbar_icon'] = 1;
$conf['plugin']['tag']['list_tags_of_subns'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['gitbacked']['repoPath'] = './data/gitrepo';
$conf['plugin']['gitbacked']['repoWorkDir'] = './data/gitrepo';
$conf['datadir'] = './data/pages';
$conf['mediadir'] = './data/media';

// end auto-generated content

// load a local_private.php and overwrite above properties if they exist in the private file. Added by: Richard Mahn
if(file_exists(dirname(__FILE__).'/local_private.php')) {
	require(dirname(__FILE__).'/local_private.php');
}
