#!/bin/sh
#
# This hook should be placed in a bare tS translation repository and will
# notify the gitmerge plugin that updates are available.
#
# Change URL to the base DokuWiki url where the plugin is installed.
#

# set base DokuWiki URL
URL=http://test.door43.org/

# ***DO NOT CHANGE ANYTHING BELOW THIS LINE***

# trigger indexing
echo Triggering translation indexing.

# parse variables from path
PWD=$(pwd)

DIRS=(${PWD//\// })
LAST=$((${#DIRS[@]} - 1))
PROJECT_LANG=${DIRS[LAST]}
unset DIRS[LAST]
((LAST--))
DEVICE=$(echo ${DIRS[LAST]} | sed 's/[^a-zA-Z0-9]//g')
unset DIRS
unset LAST

DIRS=(${PROJECT_LANG//-// })
LAST=$((${#DIRS[@]} - 1))
LANG=$(echo ${DIRS[LAST]} | sed 's/[^a-zA-Z0-9]//g')
unset DIRS[LAST]
((LAST--))
PROJECT=$(echo ${DIRS[LAST]} | sed 's/[^a-zA-Z0-9]//g')
unset DIRS
unset LAST

# get file list
FILES=$(git diff --name-only HEAD^ HEAD | grep '\.txt$' | tr "\\n" "," | sed 's/\//-/g' | sed 's/\.txt//g' | sed 's/,$//'; echo '')

# set params
PARAMS=$(echo call=door43gitmerge\&action=mark-updated\&lang=$LANG\&project=$PROJECT\&device=$DEVICE\&files=$FILES)

curl -H "X-Requested-With: XMLHttpRequest" --request POST --data "$PARAMS" --url $URL/lib/exe/ajax.php -v